# Generated by Django 4.1.2 on 2022-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Famous women', 'verbose_name_plural': 'Famous women'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
    ]
